[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Flox User <some-email@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.12.1"
